#deployment do mongo db
apiVersion: apps/v1
kind: Deployment
metadata:
  name: convtemp
spec:
  selector:
    matchLabels:
      app: convtemp
  template:
    metadata:
      labels:
        app: convtemp
    spec:
      containers:
        - image:  ralou/api-conversao:v1
          name:  convtemp
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: convtemp
spec:
  selector:
     app: convtemp
  ports: 
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer
